### ISSUE TITLE
BasicCliClient is not compatible with current Basic CLI

### ISSUE THREAD

**Issue by fwgreen** [agu-z/roc-pg#9]
Tries (and fails) to connect with `basic-cli 0.8.1` but has type mismatch errors with `0.10.0`.

**Comment by agu-z** [comment]
@fwgreen Thanks for reporting. I updated the examples to the new version of basic-cli and they seem to be working fine: https://github.com/agu-z/roc-pg/blob/main/examples/query.roc

**Comment by fwgreen** [comment]
The type mismatches are all gone.  Didn't realize I could have lived without the `Task.attempt` section.  Thanks for all your efforts.
